#!/bin/sh
# Regenerate the three resume images from Dockerfile.run.
#
# WHY THIS EXISTS. A run's output tree is named after the job that produced it,
# so a relaunched job gets an empty tree and re-samples 233 targets that are
# already on disk -- five hours to reproduce files that already exist. Pointing
# a new job at an existing tree needs FB_RUN_LABEL, and the platform holds
# environment variables per repository rather than per job, so the label has to
# be baked into the image: one image per experiment.
#
# WHY IT IS GENERATED RATHER THAN WRITTEN. Three hand-copied Dockerfiles are
# three chances for the copies to drift, and this project has already been bitten
# by configuration held in two places disagreeing -- a config file that claimed
# use_template: true for a run that had templates off. Generating them makes the
# three byte-identical to Dockerfile.run except for the one ENV line, and makes
# that checkable: `sh docker/make_resume_images.sh --check`.
#
# WHAT IT DOES NOT CHANGE. The three experiments still run the same commit, the
# same code and the same computation. What differs is the directory each writes
# into -- which already differed, by job id, before any of this.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
base="$here/Dockerfile.run"

# Read before the list replaces the positional parameters, or the mode is taken
# from the first entry of the list and --check silently rewrites the files it was
# asked to inspect.
check=${1:-}
status=0

# One line per experiment: <suffix> <run label>. The labels name the output trees
# that the 2026-08-18 runs left 99% complete; the residual pass fills the rest.
set -- \
    "run1 d613be22-de1b-40cf-842b-084b5260ece8" \
    "run2 9d5deeb3-4414-423b-acf9-b059bc81f5f2" \
    "run3 e641d514-0276-4ef0-929b-f57f8020183d"

for pair in "$@"; do
    suffix=${pair%% *}
    label=${pair#* }
    out="$here/Dockerfile.$suffix"
    tmp="$out.tmp$$"

    # The ENV goes immediately before CMD: last write wins in a Dockerfile, so
    # placing it after every other ENV means nothing above can quietly shadow it.
    awk -v label="$label" '
        /^CMD / && !done {
            print "# Resume an existing output tree instead of starting an empty one."
            print "# GENERATED by docker/make_resume_images.sh -- edit Dockerfile.run,"
            print "# then regenerate; do not edit this file by hand."
            print "ENV FB_RUN_LABEL=" label
            print ""
            done = 1
        }
        { print }
    ' "$base" > "$tmp"

    if [ "$check" = "--check" ]; then
        if cmp -s "$tmp" "$out"; then
            echo "ok      $(basename "$out")"
        else
            echo "STALE   $(basename "$out") -- regenerate with: sh docker/make_resume_images.sh"
            status=1
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$out"
        echo "wrote   $(basename "$out")  FB_RUN_LABEL=$label"
    fi
done

exit $status
